baseURL = 'https://damiansblog.com'
locale = 'en-us'
title = 'Damian Kozakiewicz'
theme = "bootstrap"
googleAnalytics = "G-ECDF3ESVLR"

[params]
  twitterHandle = "damiankozakiew1"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true

